### ISSUE TITLE
Remove .bbl and .blg file

### ISSUE THREAD

**Issue by Danghor** [karlstroetmann/Algorithms#43]
The .bbl and .blg files are generated from the .bib file and are therefore redundant.

**Comment by karlstroetmann** [comment]
Ok, dann werde ich die löschen.

**Comment by Danghor** [comment]
Fixed by a4a43c8ceecf6c5f380664d7821ff346414d6d6c and 1814a59b760fa2776a8ad4ef972a92f48b5ed113
