### ISSUE TITLE
Question about Big O notation

### ISSUE THREAD

**Issue by Danghor** [karlstroetmann/Algorithms#48]
I am using algorithms.pdf from commit 8dd0681.
On page 14, in the proofs for propositions 4 and 5, it says that constants c1 and c2 are elements of &#8477; instead of &#8477;<sub>+</sub>. Why is that the case, since on page 10, Definition 1 uses &#8477;<sub>+</sub>?

**Comment by karlstroetmann** [comment]
These constants are positive.  Hence they are in ℝ+.  I have fixed the lecture notes appropriately.
